[project]
name = "rainbow-pick"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pick>=2.4.0",
]

[dependency-groups]
dev = [
    "rainbow-pick",
]

[tool.uv.sources]
rainbow-pick = { workspace = true }
